### ISSUE TITLE
TypeError: Cannot read property 'page' of undefined when using gatsby develop

### ISSUE THREAD

**Issue by babbins** [wardpeet/gatsby-plugin-static-site#10] opened 2019-09-03 15:23 UTC
Hello! I've managed to get this plugin working as expected using `gatsby build && gastby serve`. However, when attempting to test the app in development mode ,`gatsby develop`, I run into this breaking error:
```
×
TypeError: Cannot read property 'page' of undefined
children
.cache/root.js:44
  41 | // Resetting `basepath`/`baseuri` keeps current behaviour
  42 | // to not introduce breaking change.
  43 | // Remove this in v3
> 44 | const RouteHandler = props => (
  45 |   <BaseContext.Provider
  46 |     value={{
  47 |       baseuri: `/`,

EnsureResources.render
.cache/ensure-resources.js:63
  60 | }
  61 | // Check if location has changed on a page using internal routing
  62 | // via matchPath configuration.
> 63 | if (
  64 |   this.state.location.key !== nextState.location.key &&
  65 |   nextState.pageResources.page &&
  66 |   (nextState.pageResources.page.matchPath ||


.cache/app.js:40
  37 |  *
  38 |  * Let's warn if we find service workers in development.
  39 |  */
> 40 | if (`serviceWorker` in navigator) {
  41 |   navigator.serviceWorker.getRegistrations().then(registrations => {
  42 |     if (registrations.length > 0)
  43 |       console.warn(
__trace__
node_modules/@bugsnag/browser/dist/bugsnag.js:2211
```
I believe [this user](https://github.com/wardpeet/gatsby-plugin-static-site/issues/6#issuecomment-526155941) is running into the same error.

Please let me know if I can provide anymore information!

**Comment by apaniel** [comment] 2019-09-04 12:55
@babbins what version of gatsby and what version of the plugin are you using?

**Comment by babbins** [comment] 2019-09-04 15:20
Ah, right:
```
gatsby: 2.15.0
gatsby-plugin-static-site: 0.1.1
```

**Comment by apaniel** [comment] 2019-09-06 07:53
I have found that the `loadPageSync` is returning undefined because `loadPage` has not been called for that loader.
A change made in https://github.com/gatsbyjs/gatsby/pull/16122 changes the loader in window from `loader` to `publicLoader`, but the loader being called in `production-app` to load the page -> `loader.loadPage(browserLoc.pathname).then(page => {` is the loader, not the public one. that is causing the call of `originalLoadPageSync` in this plugin to fail, because for the publicLoader `loadPage` has never been called at the point that it is used.

I made a local change in gatsby to see if using only the public loader in production-app would fix the issue, and it seems that navigtion is ok, there is no exception in the console, but the page goes blank

**Comment by xavivars** [comment] 2019-09-06 09:48
> I have found that the `loadPageSync` is returning undefined because `loadPage` has not been called for that loader.
> A change made in [gatsbyjs/gatsby#16122](https://github.com/gatsbyjs/gatsby/pull/16122) changes the loader in window from `loader` to `publicLoader`, but the loader being called in `production-app` to load the page -> `loader.loadPage(browserLoc.pathname).then(page => {` is the loader, not the public one. that is causing the call of `originalLoadPageSync` in this plugin to fail, because for the publicLoader `loadPage` has never been called at the point that it is used.


@apaniel90vp: That was actually fixed with the PR you're referencing: now publicLoader is used everywhere.:the loader called in production app **IS** the public one. Maybe the reason why you could only reproduce it below a certain version of Gatsby is because that's the version where that PR got merged. 

The issue about the page going blank is a different one that will need to be investigated after PR #5 gets merged. At that point, all navigation aspects will be solved, and the broken rehydrate is what will need to be investigated

**Comment by apaniel** [comment] 2019-09-06 10:11
@xavivars I am using the latest version that we can use for Gatsby 2.13.62, from 2.13.63 included and up, there is a change in manifest.webmanifest that removes the asset prefix so that causes another error.

The problem is that `loadPageSync` returns undefined if  `loadPage` has not been previously called, but `loadPage` is only being called for the loader, not for the public loader in `production-app.js`:

expose of the public loader being used by the plugin: 
![image](https://user-images.githubusercontent.com/40391767/64420128-d8125100-d09e-11e9-9cad-d4d330246cd0.png)

loadPage being used in `production-app.js`:
![image](https://user-images.githubusercontent.com/40391767/64420156-e9f3f400-d09e-11e9-8de4-29e9f71c0692.png)

I tried to change the `loader.loadPage` for `publicLoader.loadPage`, that fixes the exception, but the page still goes blank

**Comment by xavivars** [comment] 2019-09-06 10:15
My point is: loader is **already** changed by publicLoader. See:
https://github.com/gatsbyjs/gatsby/pull/16800

 If 2.13.63 introduces another problem, that other problem will need to get fixed, but the one you're talking about is already fixed

**Comment by apaniel** [comment] 2019-09-06 11:04
Now I understand, your fix for changing loader by publicLoader is in a higher version of gatsby than 2.13.63, my bad. I'm going to look into a fix for the manifest.webmanifest having the assetprefix removed to see if we can use the latest version.

I had a look at your example in s3 and I saw you were testing with the 2.9 version of gatsby and I thought in 2.13 all would be set.

Thanks for helping me clarify!

**Comment by wardpeet** [comment] 2019-09-18 06:47
Sorry for my absence, I haven't read through the issue yet but I'll make sure that it works again this week, I hope to get a new release out tomorrow or the day after.

**Comment by xavivars** [comment] 2019-09-27 17:54
Temporarily, while #9 and #11 get merged I've published a _fork_ of this plug-in with both PRs merged as https://www.npmjs.com/package/@xavivars/gatsby-plugin-static-site

**Comment by fodkastir** [comment] 2019-10-27 03:21
Hi @xavivars, thanks for publishing your fork. Unfortunately, I tried your fork and found it doesn't work with --prefix-paths. Do you have any clue about where I should start to look at? I can try to submit a PR in your fork if I find a fix.

**Comment by fodkastir** [comment] 2019-10-28 15:37
Hi @apaniel90vp Have you got this plugin working successfully? If so, could you let me know which version of Gatsby you are using? Thanks!

**Comment by apaniel** [comment] 2019-10-28 15:42
hi @fodkastir, I have it working with 2.15.28, the --prefix-paths is something we didn't take into account as we are not using it

**Closed as completed** 2019-11-17 19:06 UTC
